### ISSUE TITLE
Hello, Minecraft crashed while loading the mod

### ISSUE THREAD

**Issue by Theflowyears** [ROMVoid95/Interstellar-Exoplanets#26]
It reported an error and crashed my Minecraft just because it was loaded normally...
Attach the game log.
[2020-07-30-4.log](https://github.com/ROMVoid95/Interstellar-Exoplanets/files/4999592/2020-07-30-4.log)

**Comment by mMONTAGEe** [comment]
You need report issue with template

**Comment by mMONTAGEe** [comment]
this one wont be accepted
