### ISSUE TITLE
Mod Doen't Load And Crashes My Game

### ISSUE THREAD

**Issue by QuantumSD** [ROMVoid95/Interstellar-Exoplanets#27]
Hi, so I saw this mod today and I wanted to add it to my other mods but the mod crashes when Minecraft tries to load it, I tried other versions but nothing helps. Here is the crash report:
[crash-2020-07-31_15.38.26-client.txt](https://github.com/ROMVoid95/Interstellar-Exoplanets/files/5010772/crash-2020-07-31_15.38.26-client.txt)

**Comment by mMONTAGEe** [comment]
people. please use the damn template to report

**Comment by ROMVoid95** [comment]
@PowerGamesReal 
```
As of 8/1/2020
Please use AsmodeusCore 0.0.16
This mod as NOT been updated to be compatible with
AsmodeusCore 0.0.17
```

**Comment by QuantumSD** [comment]
> @PowerGamesReal
> 
> ```
> As of 8/1/2020
> Please use AsmodeusCore 0.0.16
> This mod as NOT been updated to be compatible with
> AsmodeusCore 0.0.17
> ```
ok I will try that

**Comment by ROMVoid95** [comment]
however, it will also conflict with the newest galaxysapce version, which needs 0.0.17
i plan on updating exoplanets today that will fix this
