### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by linuxcorrupter** [ROMVoid95/Interstellar-Exoplanets#28]
## Crash Report (Not for Issues / Bugs - Please use Issue Report template for Issues / Bugs)
[ Lines between [ ] (square brackets) should be removed before posting ]</br>

[ #### Important:
 - If you decide to delete this template entirely, your issue will be closed. 
 - If you do not provide a crash-log posted to the haste link below, this issue will be closed.
### Use [This Haste Server](https://haste.romvoid.dev) These links are set to never expire ]</br>

[ Please look at other open or closed Crash Reports to make sure that you are not creating a duplicate ]</br>

#### CrashLog Haste Link:
https://haste.romvoid.dev/yexaqigeke.reasonml

**Comment by ROMVoid95** [comment]
update AsmodeusCore to 0.0.17

**Comment by linuxcorrupter** [comment]
thanks
