### ISSUE TITLE
[ISSUE] its missing a body icon for kepler1649c & yzcetib & yzcetic & yzcetid

### ISSUE THREAD

**Issue by Ayukii11** [ROMVoid95/Interstellar-Exoplanets#29]
Hello, 
recently my game crashed when I press M to display the map.
I asked into MJRLegends (Extraplanets) support and it redirected me to you. According to him, its «missing a body icon for kepler1649c & yzcetib & yzcetic & yzcetid» (Message from him)

[crash-2020-07-26_02.54.52-client.txt](https://github.com/ReadOnly-Mods/Interstellar-Exoplanets/files/5071872/crash-2020-07-26_02.54.52-client.txt)

[latest.log](https://github.com/ReadOnly-Mods/Interstellar-Exoplanets/files/5071879/latest.log)

[debug.log](https://github.com/ReadOnly-Mods/Interstellar-Exoplanets/files/5071880/debug.log)

Thanks !

**Comment by ROMVoid95** [comment]
you are using the dev version of the mod, please use the non-dev jar.
