### ISSUE TITLE
Crashed while loading

### ISSUE THREAD

**Issue by mMONTAGEe** [ROMVoid95/Interstellar-Exoplanets#35]
## Crash Report (Not for Issues / Bugs - Please use Issue Report template for Issues / Bugs)
[ Lines between [ ] (square brackets) should be removed before posting ]</br>

[ #### Important:
 - If you decide to delete this template entirely, your issue will be closed. 
 - If you do not provide a crash-log posted to the haste link below, this issue will be closed.
### Use [This Haste Server](https://haste.romvoid.dev) These links are set to never expire ]</br>

[ Please look at other open or closed Crash Reports to make sure that you are not creating a duplicate ]</br>

#### Any useful information or comments regarding the crash:
Crashed with newest ver of asmodeuscore and craftweaker zollern galaxy

#### CrashLog Haste Link: https://haste.romvoid.dev/edalamogoz.sql
[ haste.romvoid.dev link here ]

**Comment by ROMVoid95** [comment]
use previous version of AsmodeusCore
